import { chromium } from "playwright";
const b = await chromium.launch({ args:["--use-gl=swiftshader"] });
const p = await (await b.newContext({ viewport:{width:1440,height:900} })).newPage();
const errs=[]; p.on("console",m=>{if(m.type()==="error")errs.push(m.text())}); p.on("pageerror",e=>errs.push("PE:"+e.message));
await p.goto("http://localhost:3737/en",{waitUntil:"commit"});
const base="/private/tmp/claude-501/-Volumes-DISQUE-SADY-13-SCHOOL-01-UX-UI-STAGE-TREEOSK-TREEOSK-DESIGN-SITE/e9bc403c-9a5d-41d9-8e3c-3b89cb08c9c5/scratchpad";
await p.waitForTimeout(400); await p.screenshot({path:`${base}/boot-early.png`});
await p.waitForTimeout(3600); await p.screenshot({path:`${base}/boot-intro.png`});
console.log("ERRORS:", errs.length?errs.slice(0,6).join(" | "):"none");
await b.close();
