import { chromium } from "playwright";
const [,, url, out] = process.argv;
const b = await chromium.launch({ args:["--use-gl=swiftshader"] });
const ctx = await b.newContext({ viewport:{width:1440,height:900} });
const p = await ctx.newPage();
await p.addInitScript(() => { try{ sessionStorage.setItem("introSeen","1"); }catch(e){} });
await p.goto(url, { waitUntil:"networkidle" });
await p.waitForTimeout(4500);
await p.screenshot({ path: out });
await b.close(); console.log("ok");
