import { chromium } from "playwright";
const [,, url, out] = process.argv;
const b = await chromium.launch({ args:["--use-gl=swiftshader"] });
const ctx = await b.newContext({ viewport:{width:1440,height:900}, reducedMotion:"reduce" });
const p = await ctx.newPage();
await p.goto(url, { waitUntil:"networkidle" });
await p.evaluate(() => document.querySelector('#instore')?.scrollIntoView());
await p.waitForTimeout(1500);
await p.screenshot({ path: out });
await b.close(); console.log("ok");
